"""update integer columns to bigint to support larger values

Revision ID: 003
Revises: 002
Create Date: 2025-08-31 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Update base model id columns
    op.alter_column('users', 'id', type_=sa.BigInteger())
    op.alter_column('subscriptions', 'id', type_=sa.BigInteger())
    op.alter_column('analytics_events', 'id', type_=sa.BigInteger())
    op.alter_column('user_sessions', 'id', type_=sa.BigInteger())
    op.alter_column('crisis_events', 'id', type_=sa.BigInteger())
    
    # Update foreign key columns
    op.alter_column('subscriptions', 'user_id', type_=sa.BigInteger())
    op.alter_column('analytics_events', 'user_id', type_=sa.BigInteger())
    op.alter_column('user_sessions', 'user_id', type_=sa.BigInteger())
    op.alter_column('crisis_events', 'user_id', type_=sa.BigInteger())
    
    # Update other integer columns that might exceed 32-bit limits
    op.alter_column('users', 'age', type_=sa.BigInteger())
    op.alter_column('users', 'ping_hours_start', type_=sa.BigInteger())
    op.alter_column('users', 'ping_hours_end', type_=sa.BigInteger())
    
    op.alter_column('subscriptions', 'daily_messages_used', type_=sa.BigInteger())
    op.alter_column('subscriptions', 'daily_messages_limit', type_=sa.BigInteger())
    
    op.alter_column('analytics_events', 'message_length', type_=sa.BigInteger())
    op.alter_column('analytics_events', 'token_count', type_=sa.BigInteger())
    
    op.alter_column('user_sessions', 'message_count', type_=sa.BigInteger())
    op.alter_column('user_sessions', 'duration_minutes', type_=sa.BigInteger())
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Downgrade other integer columns
    op.alter_column('user_sessions', 'duration_minutes', type_=sa.Integer())
    op.alter_column('user_sessions', 'message_count', type_=sa.Integer())
    
    op.alter_column('analytics_events', 'token_count', type_=sa.Integer())
    op.alter_column('analytics_events', 'message_length', type_=sa.Integer())
    
    op.alter_column('subscriptions', 'daily_messages_limit', type_=sa.Integer())
    op.alter_column('subscriptions', 'daily_messages_used', type_=sa.Integer())
    
    op.alter_column('users', 'ping_hours_end', type_=sa.Integer())
    op.alter_column('users', 'ping_hours_start', type_=sa.Integer())
    op.alter_column('users', 'age', type_=sa.Integer())
    
    # Downgrade foreign key columns
    op.alter_column('crisis_events', 'user_id', type_=sa.Integer())
    op.alter_column('user_sessions', 'user_id', type_=sa.Integer())
    op.alter_column('analytics_events', 'user_id', type_=sa.Integer())
    op.alter_column('subscriptions', 'user_id', type_=sa.Integer())
    
    # Downgrade base model id columns
    op.alter_column('crisis_events', 'id', type_=sa.Integer())
    op.alter_column('user_sessions', 'id', type_=sa.Integer())
    op.alter_column('analytics_events', 'id', type_=sa.Integer())
    op.alter_column('subscriptions', 'id', type_=sa.Integer())
    op.alter_column('users', 'id', type_=sa.Integer())
    
    # ### end Alembic commands ###