"""add prompt history table

Revision ID: 99e4d9d3bb7c
Revises: 003
Create Date: 2025-09-01 22:13:14.266310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e4d9d3bb7c'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # prompt_history table and BigInteger columns are already created in migration 000
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # All tables and columns are managed in migration 000
    pass
    # ### end Alembic commands ###